apiVersion: citrix.citrix.com/v1alpha1
kind: Citrix-adc-cpx-istio-sidecar-injector-operator
metadata:
  name: citrix-adc-cpx-istio-sidecar-injector-operator-sample
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-cpx-istio-sidecar-injector/values.yaml
  cpxProxy:
    EULA: false
    cpxSidecarMode: true
    image: quay.io/citrix/citrix-k8s-cpx-ingress
    imagePullPolicy: IfNotPresent
    licenseServerPort: 27000
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    tag: 13.0-47.22
  istioAdaptor:
    ADMFingerPrint: null
    ADMIP: null
    coeURL: null
    image: quay.io/citrix/citrix-istio-adaptor
    imagePullPolicy: IfNotPresent
    netscalerUrl: http://127.0.0.1
    proxyType: sidecar
    secureConnect: true
    tag: 1.2.1
  istioPilot:
    SAN: spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account
    insecureGrpcPort: 15010
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
  sidecarWebHook:
    imagePullPolicy: IfNotPresent
    webhookImage: gcr.io/istio-release/sidecar_injector
    webhookImageVersion: 1.0.0
  webhook:
    injectionLabelName: cpx-injection
  
  
