# permissions for end users to view citrix-adc-cpx-istio-sidecar-injector-operators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: citrix-adc-cpx-istio-sidecar-injector-operator-viewer-role
rules:
- apiGroups:
  - citrix.citrix.com
  resources:
  - citrix-adc-cpx-istio-sidecar-injector-operators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citrix.citrix.com
  resources:
  - citrix-adc-cpx-istio-sidecar-injector-operators/status
  verbs:
  - get
