apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.1
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: citrix-adc-cpx-istio-sidecar-injector-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: In Istio service mesh, a sidecar proxy runs alongside application pods and it intercepts and manages incoming and outgoing traffic for applications. Citrix ADC CPX can be deployed as the sidecar proxy in application pods. A sidecar proxy applies the configured routing policies or rules to the ingress and egress traffic from the pod.
  displayName: citrix-adc-cpx-istio-sidecar-injector-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Citrix
  - ADC
  - Istio
  - sidecar
  links:
  - name: Citrix Adc Cpx Istio Sidecar Injector Operator
    url: https://citrix-adc-cpx-istio-sidecar-injector-operator.domain
  maintainers:
  - email: ajeeta.shakeet@citrix.com
    name: AjeetaShakeet
  maturity: alpha
  provider:
    name: citrix
    url: citrix.com
  version: 0.0.0
